name: Manual Deploy to S3 + CloudFront

on:
  workflow_dispatch: # Запуск тільки вручну з GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонування коду
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Конфігурація AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Синхронізація файлів з S3
      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --acl public-read

      # 4. CloudFront cache invalidation
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
